### PR TITLE
delete person

### PR DESCRIPTION
**Pull request by cartoloupe**
this button removes the person from the db.
useful for clearing out generated people.
- [x] need to figure out a way to only display this button in the people.html view, but not the pairs.html view

### CODE REVIEW

**Comment by cartoloupe** [comment]
Now uses a global to keep track of whether the pairs or people page is displayed, and during routing this global is set.

cc: @nicolasmccurdy

**Comment by nickserv** [comment]
Nice work. I figured out how to check the current page without those global variables, and I merged master into this branch. Let's see what we can do to clean up the logic and the UI now that the remove pair buttons are merged in.

**Comment by cartoloupe** [comment]
Thanks for figuring that out! Excellent use of `Router.current().route.getName()` :+1: 

The merge of #16 puts the remove pair button on the right of each pair, so I took the button out of the person template.

**Comment by nickserv** [comment]
Do you think it would be useful to offer the ability to delete unpaired people from the pairs page?

**Comment by cartoloupe** [comment]
I thought about this, and it led me to the idea of removing people from pairing, but only being able to delete them on the people page; this would mean that there would be an additional "bin" to put people in -- one that indicates that they are or are not participating in the current pairings. Let me open an issue for this (opened #36).

**Pull request merged**
