### PR TITLE
Suggested fix for #64

### PR DESCRIPTION
**Pull request by degoeym**
This adds a new navbar to the site layout. Tweaks can be made for styling and whatnot, but the main thing this solves is the login dropdown going outside the main viewport on the right.

### CODE REVIEW

**Comment by cartoloupe** [comment]
@degoeym Looks good - the whole navbar is now in its own meteor template, and there is no need to hide the login buttons in the full screen view anymore.

I'm adding a few tweaks for the styling; see screenshot below:
screen shot 2015-07-21 at 11 20 23 pm

**Comment by degoeym** [comment]
I'd almost rather bring the text out of the navbar, and possibly even the logo if you're wanting to stick with full color. Going with a white background on the logo is part of why I suggested producing black, white, and possibly grey versions of it, and in different sizes to avoid scaling it to meet certain needs.

The question then is: what else do we put in the navbar to make it worth having up there?

**Comment by degoeym** [comment]
Made some changes. Still wanna work with the logo, but I made the text for the admin/login item on the right match and lineup better with the rest of the text on the navbar.

**Comment by cartoloupe** [comment]
You mean something like this?:
screen shot 2015-07-22 at 12 14 11 am

I thought the navbar was needed to get {{>loginButtons}} to expand within the bounds of the window, but if there's another way, then yes, I guess the navbar isn't needed. But looking at the above screenshots I like how the navbar separates out the logo and the heading description from the other more frequently changing data.

**Comment by cartoloupe** [comment]
Discussed with @degoeym; going with the following for now; future work to include changing logo background color and figuring out custom [TWBS navbar colors](http://stackoverflow.com/questions/18529274/change-navbar-color-in-twitter-bootstrap-3).

screen shot 2015-07-22 at 12 40 53 am

**Pull request merged**
