### PR TITLE
pair()

### PR DESCRIPTION
**Pull request by cartoloupe**
WIP

### CODE REVIEW

**Comment by nicolasmccurdy** [comment]
http://en.wikipedia.org/wiki/Marathon

**Comment by nickserv** [comment]
The app seems to be crashing as of 65a8bd1.

**Comment by cartoloupe** [comment]
@nicolasmccurdy Reverted back to latest working copy; working on d3 stuff in another branch

**Comment by nickserv** [comment]
Thanks, I'll take a look at this pull request in detail at some point today.

**Comment by nickserv** [comment]
Awesome progress! I would like us to display people in a similar way though, so how about splitting the pairs into two columns?

**Pull request merged**
