### PR TITLE
Autoscroll to unpaired

### PR DESCRIPTION
**Pull request by cartoloupe**
In cases where there is a long list of pairs on the pairs page, clicking the counter buttons will scroll to and from the paired/unpaired sections.

Gif to come if this becomes any more relevant.

### CODE REVIEW

**Comment by nickserv** [comment]
If I'm understanding the code correctly, it seems like we're including the jQuery scrollTo plugin without using it (unless it's automatically activated).

**Comment by cartoloupe** [comment]
Oh yeah, I switched away from scrollTo for some reason. I'll remove the package. (Good catch!)

**Comment by cartoloupe** [comment]
I think this can be merged; though it's not obvious that clicking the badge button will scroll to the other section.

**Comment by cartoloupe** [comment]
Closing; like the wings of an ostrich

screen shot 2015-05-17 at 2 25 40 am

**Pull request closed without merging**
