### PR TITLE
add reminders to pairing pages, to help facilitate the event

### PR DESCRIPTION
**Pull request by cartoloupe**
notes from the 5/9 event

### CODE REVIEW

**Comment by nickserv** [comment]
This is an interesting idea, but I personally think it would be better to keep this on the Pair Columbus website.

Some reasons:
1. Keeps all Pair Columbus related information in one place.
2. Can be accessed on their computer (even if the instance of the Pairs app isn't publicly accessible).
3. Keeps the UI simple.
4. Makes it easier to generalize the app to make it useful to other organizations (by keeping more Pair Columbus specific information outside of the app).

What do you think?

**Comment by cartoloupe** [comment]
Totally agree. This information: 
- what pairing is
- announcements
- wrapup

should go on the Pair Columbus site instead. 

(The fact that this PR arose from the last event though, seems to indicate that some kind of solution should be provided from the pairs page. Switching displays/remembering to make announcements is something that we always have an opportunity to forget. What if the page allowed feeds from other sites, and have Pair Columbus publish announcements and other snippets?)

**Comment by nickserv** [comment]
We could split the screen between the pairs app and website content (or we could use a second screen).

**Comment by nickserv** [comment]
By the way, feel free to make an issue on [the website's repo](https://github.com/paircolumbus/paircolumbus.github.io) if you want more sections of content added.

**Pull request closed without merging**
