### PR TITLE
wip: tests

### LINKED ISSUE #19: tests
### unit tests
- [ ] server methods
### client side
- [ ] buttons
- [ ] select -> remove pair -> create new pair

### PR DESCRIPTION
**Pull request by cartoloupe**
fixes #19

currently, this test never completes, figuring out why...

### CODE REVIEW

**Comment by nickserv** [comment]
CoffeeScript was being used for the test script, but the `coffeescript` package wasn't added to the Meteor app. I'm not sure why this caused a stall, but it does work if you use JavaScript instead. I'll convert this to JavaScript now.

**Comment by cartoloupe** [comment]
Thanks! The test runs now. I started on a happy path test of pairing 5 people. The test in Velocity is always passing, even if there are errors, which show up in the javascript console. I believe I'm running into some timing issues.

**Comment by nickserv** [comment]
You're testing asynchronous code, but Mocha (the test framework) does not realize that. Because of this, Mocha terminates the test synchronously, so it acts as if everything passes because the potentially failing code is being run asynchronously after the test ends and reports that it is passing.

Fortunately, Mocha lets you [test asynchronous code with callbacks](http://mochajs.org/#asynchronous-code).

**Comment by cartoloupe** [comment]
Ok, good to know. I've gotten most of the test to pass, but still having problems with `chai.assert.equal(1, People.find({ pairee: null }).count());`.

The iframe shows no people in the pairs section, yet the number of pairs is shown to be 2. I wonder if this  has anything to do with code being executed on the server vs client side...

**Comment by nickserv** [comment]
Those tests are in the client directory, so they should only run on the client side.

**Comment by cartoloupe** [comment]
@nicolasmccurdy The test passes now. I think we can finally merge this tests branch in!

**Pull request merged**
